### Regression problem to predict salary

In [2]:
#importing libraries

import numpy as np
import pandas as pd
import pickle, datetime

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [3]:
#importing dataset into dataframe

data = pd.read_csv("churn_modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#dropping columns RowNumber, CustomerId, Surname

data = data.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#splitting data into train and test set.

x = data.drop(columns=['EstimatedSalary'])
y = data['EstimatedSalary']


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500, 10)
(2500, 10)
(7500,)
(2500,)

In [6]:
x_train['Gender'].head()

4901      Male
4375      Male
6698    Female
9805      Male
1101      Male
Name: Gender, dtype: str

In [7]:
#encoding categorical feature 'Gender'

label_encoder = LabelEncoder()

x_train['Gender'] = label_encoder.fit_transform(x_train['Gender'])
x_test['Gender'] = label_encoder.transform(x_test['Gender'])

In [8]:
x_train['Gender'].head()

4901    1
4375    1
6698    0
9805    1
1101    1
Name: Gender, dtype: int64

In [9]:
#encoding categorical feature 'Geography'

onehot_encoder = OneHotEncoder()

geography_train_arr = onehot_encoder.fit_transform(x_train[['Geography']]).toarray()
geography_test_arr = onehot_encoder.transform(x_test[['Geography']]).toarray()

geo_train_df = pd.DataFrame(geography_train_arr, columns=onehot_encoder.get_feature_names_out())
geo_test_df = pd.DataFrame(geography_test_arr, columns=onehot_encoder.get_feature_names_out())

In [10]:
train_df = pd.concat([x_train.reset_index(drop=True),geo_train_df], axis=1)
train_df = train_df.drop(columns=['Geography'])
train_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,673,1,59,0,178058.06,2,0,1,1,1.0,0.0,0.0
1,850,1,41,8,60880.68,1,1,0,0,0.0,1.0,0.0
2,725,0,31,6,0.00,1,0,0,0,1.0,0.0,0.0
3,644,1,33,7,174571.36,1,0,1,0,1.0,0.0,0.0
4,703,1,29,9,0.00,2,1,0,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7495,768,1,54,8,69712.74,1,1,1,0,1.0,0.0,0.0
7496,682,0,58,1,0.00,1,1,1,0,1.0,0.0,0.0
7497,735,0,38,1,0.00,3,0,0,1,1.0,0.0,0.0
7498,667,1,43,8,190227.46,1,1,0,1,1.0,0.0,0.0
7499,697,1,51,1,147910.30,1,1,1,0,0.0,1.0,0.0

In [11]:
test_df = pd.concat([x_test.reset_index(drop=True),geo_test_df], axis=1)
test_df = test_df.drop(columns=['Geography'])
test_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,596,1,32,3,96709.07,2,0,0,0,0.0,1.0,0.0
1,623,1,43,1,0.00,2,1,1,0,1.0,0.0,0.0
2,601,0,44,4,0.00,2,1,0,0,0.0,0.0,1.0
3,506,1,59,8,119152.10,2,1,1,0,0.0,1.0,0.0
4,560,0,27,7,124995.98,1,1,1,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2495,645,0,55,1,133676.65,1,0,1,0,0.0,0.0,1.0
2496,569,0,51,3,0.00,3,1,0,1,0.0,0.0,1.0
2497,768,1,25,0,78396.08,1,1,1,0,1.0,0.0,0.0
2498,690,0,36,6,110480.48,1,0,0,0,1.0,0.0,0.0
2499,604,0,25,5,157780.84,2,1,1,0,0.0,1.0,0.0

In [12]:
#scaling the input features

scaler = StandardScaler()

x_train_arr = scaler.fit_transform(train_df)
x_test_arr = scaler.transform(test_df)

In [13]:
#saving ojects to pickle files

with open("onehot_encoder_regression.pkl", "wb") as file_obj:
    pickle.dump(onehot_encoder,file_obj)

with open("scaler_regression.pkl", "wb") as file_obj:
    pickle.dump(scaler, file_obj)

with open("label_encoder_regression.pkl", "wb") as file_obj:
    pickle.dump(label_encoder, file_obj)

In [14]:
#regression model building

model = Sequential([
    Dense(units=64, activation="relu", input_shape=(x_train_arr.shape[1],)),
    Dense(units=32, activation="relu"),
    Dense(units=1) #linear activation
])

model.summary()

d:\End_To_End_Projects\Customer_Churn_Classification\churnenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
#compiling model

model.compile(
    optimizer="adam",
    loss="mae",
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [16]:
#callbacks

tensorboard_callback = TensorBoard(log_dir="reglog/fit/"+datetime.datetime.now().strftime("%Y-%m-%d_%H_%M_%S"), histogram_freq=1)

earlystopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True, mode="min")

In [17]:
#model training

model.fit(x_train_arr, y_train, validation_data=(x_test_arr, y_test), epochs=100, verbose=True, callbacks=[tensorboard_callback, earlystopping_callback])

Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0000e+00 - loss: 100621.7656 - val_accuracy: 0.0000e+00 - val_loss: 98171.1719
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 99952.8359 - val_accuracy: 0.0000e+00 - val_loss: 96811.8750
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 97543.7031 - val_accuracy: 0.0000e+00 - val_loss: 93218.8203
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 92631.5234 - val_accuracy: 0.0000e+00 - val_loss: 87037.9453
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 85321.9688 - val_accuracy: 0.0000e+00 - val_loss: 78971.8516
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 76560.8672 - val_accuracy: 0.0000e+00 - val_loss: 70352.0312
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 67743.4062 - val_accuracy: 0.0000e+00 - val_loss: 62547.9727
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 60351.4570 - val_accuracy: 0.0000e+00 - val_loss: 56663.8320
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 55180.1797 - val_accuracy: 0.0000e+00 - val_loss: 53028.4102
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 52248.2969 - val_accuracy: 0.0000e+00 - val_loss: 51299.7266
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50937.2930 - val_accuracy: 0.0000e+00 - val_loss: 50718.6055
Epoch 12/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 50455.0469 - val_accuracy: 0.0000e+00 - val_loss: 50539.6250
Epoch 13/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50268.0820 - val_accuracy: 0.0000e+00 - val_loss: 50485.5664
Epoch 14/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50186.0273 - val_accuracy: 0.0000e+00 - val_loss: 50452.6992
Epoch 15/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50129.5312 - val_accuracy: 0.0000e+00 - val_loss: 50421.7539
Epoch 16/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50085.1797 - val_accuracy: 0.0000e+00 - val_loss: 50394.2109
Epoch 17/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50049.5547 - val_accuracy: 0.0000e+00 - val_loss: 50370.1133
Epoch 18/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 50018.9297 - val_accuracy: 0.0000e+00 - val_loss: 50334.1328
Epoch 19/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49988.8125 - val_accuracy: 0.0000e+00 - val_loss: 50307.7930
Epoch 20/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49962.9492 - val_accuracy: 0.0000e+00 - val_loss: 50289.8398
Epoch 21/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49937.4023 - val_accuracy: 0.0000e+00 - val_loss: 50267.6289
Epoch 22/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49912.6953 - val_accuracy: 0.0000e+00 - val_loss: 50245.6328
Epoch 23/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49889.6562 - val_accuracy: 0.0000e+00 - val_loss: 50226.9102
Epoch 24/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49869.4688 - val_accuracy: 0.0000e+00 - val_loss: 50220.4414
Epoch 25/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49848.4883 - val_accuracy: 0.0000e+00 - val_loss: 50197.9219
Epoch 26/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49831.0195 - val_accuracy: 0.0000e+00 - val_loss: 50189.2812
Epoch 27/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49812.9883 - val_accuracy: 0.0000e+00 - val_loss: 50176.5664
Epoch 28/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49797.2148 - val_accuracy: 0.0000e+00 - val_loss: 50160.6016
Epoch 29/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49779.9609 - val_accuracy: 0.0000e+00 - val_loss: 50151.4766
Epoch 30/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49768.4023 - val_accuracy: 0.0000e+00 - val_loss: 50139.8516
Epoch 31/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49754.7539 - val_accuracy: 0.0000e+00 - val_loss: 50129.2305
Epoch 32/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49744.3984 - val_accuracy: 0.0000e+00 - val_loss: 50120.8047
Epoch 33/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49733.4297 - val_accuracy: 0.0000e+00 - val_loss: 50109.5586
Epoch 34/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49719.4766 - val_accuracy: 0.0000e+00 - val_loss: 50104.1836
Epoch 35/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49705.7109 - val_accuracy: 0.0000e+00 - val_loss: 50088.0273
Epoch 36/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49696.9844 - val_accuracy: 0.0000e+00 - val_loss: 50083.7617
Epoch 37/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49683.5469 - val_accuracy: 0.0000e+00 - val_loss: 50080.4336
Epoch 38/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49677.3516 - val_accuracy: 0.0000e+00 - val_loss: 50076.0742
Epoch 39/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49666.3594 - val_accuracy: 0.0000e+00 - val_loss: 50070.6484
Epoch 40/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49654.0117 - val_accuracy: 0.0000e+00 - val_loss: 50060.8594
Epoch 41/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49642.3242 - val_accuracy: 0.0000e+00 - val_loss: 50052.9805
Epoch 42/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49634.2148 - val_accuracy: 0.0000e+00 - val_loss: 50049.8672
Epoch 43/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49628.2578 - val_accuracy: 0.0000e+00 - val_loss: 50042.4336
Epoch 44/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49616.1523 - val_accuracy: 0.0000e+00 - val_loss: 50045.9961
Epoch 45/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49605.8164 - val_accuracy: 0.0000e+00 - val_loss: 50029.8242
Epoch 46/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49602.5781 - val_accuracy: 0.0000e+00 - val_loss: 50028.5781
Epoch 47/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49594.1328 - val_accuracy: 0.0000e+00 - val_loss: 50021.3984
Epoch 48/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49583.6680 - val_accuracy: 0.0000e+00 - val_loss: 50026.3125
Epoch 49/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49579.2344 - val_accuracy: 0.0000e+00 - val_loss: 50032.7031
Epoch 50/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49574.5781 - val_accuracy: 0.0000e+00 - val_loss: 50024.5938
Epoch 51/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49566.3711 - val_accuracy: 0.0000e+00 - val_loss: 50024.1016
Epoch 52/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49560.7969 - val_accuracy: 0.0000e+00 - val_loss: 50014.1953
Epoch 53/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49549.1602 - val_accuracy: 0.0000e+00 - val_loss: 50006.4492
Epoch 54/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49544.9141 - val_accuracy: 0.0000e+00 - val_loss: 50009.4219
Epoch 55/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49539.6953 - val_accuracy: 0.0000e+00 - val_loss: 49996.0039
Epoch 56/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49536.2031 - val_accuracy: 0.0000e+00 - val_loss: 49997.6016
Epoch 57/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49530.2344 - val_accuracy: 0.0000e+00 - val_loss: 49993.5664
Epoch 58/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49521.6016 - val_accuracy: 0.0000e+00 - val_loss: 49998.0273
Epoch 59/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49515.4766 - val_accuracy: 0.0000e+00 - val_loss: 49995.6914
Epoch 60/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49510.4844 - val_accuracy: 0.0000e+00 - val_loss: 49990.9453
Epoch 61/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49508.0430 - val_accuracy: 0.0000e+00 - val_loss: 49985.0859
Epoch 62/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49498.8828 - val_accuracy: 0.0000e+00 - val_loss: 49995.3555
Epoch 63/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49496.1992 - val_accuracy: 0.0000e+00 - val_loss: 49988.8945
Epoch 64/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49494.0664 - val_accuracy: 0.0000e+00 - val_loss: 49988.9648
Epoch 65/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49482.6172 - val_accuracy: 0.0000e+00 - val_loss: 49991.7266
Epoch 66/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49481.9297 - val_accuracy: 0.0000e+00 - val_loss: 49993.5195
Epoch 67/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49479.2227 - val_accuracy: 0.0000e+00 - val_loss: 49983.0156
Epoch 68/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49471.7031 - val_accuracy: 0.0000e+00 - val_loss: 49986.4297
Epoch 69/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49468.0859 - val_accuracy: 0.0000e+00 - val_loss: 49991.0508
Epoch 70/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49461.9258 - val_accuracy: 0.0000e+00 - val_loss: 49985.2930
Epoch 71/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49458.1523 - val_accuracy: 0.0000e+00 - val_loss: 49980.4180
Epoch 72/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49452.3555 - val_accuracy: 0.0000e+00 - val_loss: 49974.9961
Epoch 73/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49449.6094 - val_accuracy: 0.0000e+00 - val_loss: 49976.7695
Epoch 74/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49446.3047 - val_accuracy: 0.0000e+00 - val_loss: 49984.4883
Epoch 75/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49439.9805 - val_accuracy: 0.0000e+00 - val_loss: 49990.2266
Epoch 76/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49438.2734 - val_accuracy: 0.0000e+00 - val_loss: 49981.4453
Epoch 77/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49431.9727 - val_accuracy: 0.0000e+00 - val_loss: 49979.8320
Epoch 78/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49430.0195 - val_accuracy: 0.0000e+00 - val_loss: 49983.7266
Epoch 79/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49426.5508 - val_accuracy: 0.0000e+00 - val_loss: 49989.2773
Epoch 80/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: 49425.4414 - val_accuracy: 0.0000e+00 - val_loss: 49986.8438
Epoch 81/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49419.7617 - val_accuracy: 0.0000e+00 - val_loss: 49990.3672
Epoch 82/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 49413.1758 - val_accuracy: 0.0000e+00 - val_loss: 49998.0508

In [ ]:
%load_ext tensorboard

%tensorboard --logdir "reglog/fit"

In [21]:
#evaluating model on test dataset

evaluation_loss, evalution_accuracy = model.evaluate(x_test_arr, y_test)
print(f"Evalution Loss: {evaluation_loss}")

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 49974.9961
Evalution Loss: 49974.99609375

In [22]:
#saving model in .keras file

model.save("reg_model.keras")